version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: mkdocs-material
    versions:
    - 6.2.6
    - 6.2.7
    - 6.2.8
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.1.0
    - 7.1.1
    - 7.1.2
  - dependency-name: identify
    versions:
    - 1.5.13
    - 1.5.14
    - 1.6.1
    - 2.0.0
    - 2.1.0
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
    - 20.4.2
    - 20.4.3
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.56.1
    - 4.56.2
    - 4.57.0
    - 4.58.0
    - 4.59.0
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: joblib
    versions:
    - 1.0.0
