[tool.poetry]
name = "dry-python"
version = "0.1.0"
description = "dry-python.org website"
authors = ["Artem Malyshev <proofit404@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Lektor = "^3.1"
lektor-google-analytics = "^0.1.3"

[tool.poetry.dev-dependencies]
yamllint = "^1.16"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
