[tool.poetry]
name = "dry-python"
version = "0.1.0"
description = "dry-python.org website"
authors = ["Artem Malyshev <proofit404@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
mkdocs = "^1.0.4"
mkdocs-material = "^4.6.0"

[tool.poetry.dev-dependencies]
yamllint = "^1.20"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
